# Generated by Django 5.1.5 on 2025-02-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_full_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_phone_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_postal_code',
            field=models.CharField(default='000000', max_length=10),
        ),
    ]
